export const DELETE_REQUEST = 'DELETE_REQUEST';
export const DELETE_SUCCESS = 'DELETE_SUCCESS';
export const DELETE_FAILURE = 'DELETE_FAILURE';

export const FIND_ITEMS_REQUEST = 'FIND_ITEMS_REQUEST';
export const FIND_ITEMS_SUCCESS = 'FINDS_ITEMS_SUCCESS';
export const FIND_ITEMS_FAILURE = 'FINDS_ITEMS_FAILURE';

export const FIND_ITEM_REQUEST = 'FIND_ITEM_REQUEST';
export const FIND_ITEM_SUCCESS = 'FIND_ITEM_SUCCESS';
export const FIND_ITEM_FAILURE = 'FIND_ITEM_FAILURE';

export const FIND_UNITS_REQUEST = 'FIND_UNITS_REQUEST';
export const FIND_UNITS_SUCCESS = 'FINDS_UNITS_SUCCESS';
export const FIND_UNITS_FAILURE = 'FINDS_UNITS_FAILURE';

export const FIND_UNIT_REQUEST = 'FIND_UNIT_REQUEST';
export const FIND_UNIT_SUCCESS = 'FIND_UNIT_SUCCESS';
export const FIND_UNIT_FAILURE = 'FIND_UNIT_FAILURE';

export const SAVE_UNIT_REQUEST = 'SAVE_UNIT_REQUEST';
export const SAVE_UNIT_SUCCESS = 'SAVE_UNIT_SUCCESS';
export const SAVE_UNIT_FAILURE = 'SAVE_UNIT_FAILURE';

export const SAVE_ITEM_REQUEST = 'SAVE_ITEM_REQUEST';
export const SAVE_ITEM_SUCCESS = 'SAVE_ITEM_SUCCESS';
export const SAVE_ITEM_FAILURE = 'SAVE_ITEM_FAILURE';

export const SAVE_STOCK_REQUEST = 'SAVE_STOCK_REQUEST';
export const SAVE_STOCK_SUCCESS = 'SAVE_STOCK_SUCCESS';
export const SAVE_STOCK_FAILURE = 'SAVE_STOCK_FAILURE';

export const SAVE_TRANSACTION_REQUEST = 'SAVE_TRANSACTION_REQUEST';
export const SAVE_TRANSACTION_SUCCESS = 'SAVE_TRANSACTION_SUCCESS';
export const SAVE_TRANSACTION_FAILURE = 'SAVE_TRANSACTION_FAILURE';

export const FIND_STOCKS_REQUEST = 'FIND_STOCKS_REQUEST';
export const FIND_STOCKS_SUCCESS = 'FINDS_STOCKS_SUCCESS';
export const FIND_STOCKS_FAILURE = 'FINDS_STOCKS_FAILURE';

export const FIND_STOCK_REQUEST = 'FIND_STOCK_REQUEST';
export const FIND_STOCK_SUCCESS = 'FIND_STOCK_SUCCESS';
export const FIND_STOCK_FAILURE = 'FIND_STOCK_FAILURE';

export const FIND_TRANSACTIONS_REQUEST = 'FIND_TRANSACTIONS_REQUEST';
export const FIND_TRANSACTIONS_SUCCESS = 'FINDS_TRANSACTIONS_SUCCESS';
export const FIND_TRANSACTIONS_FAILURE = 'FINDS_TRANSACTIONS_FAILURE';

export const FIND_TRANSACTION_REQUEST = 'FIND_TRANSACTION_REQUEST';
export const FIND_TRANSACTION_SUCCESS = 'FIND_TRANSACTION_SUCCESS';
export const FIND_TRANSACTION_FAILURE = 'FIND_TRANSACTION_FAILURE';

export const SUMMARY_TRANSACTION_REQUEST = 'SUMMARY_TRANSACTION_REQUEST';
export const SUMMARY_TRANSACTION_SUCCESS = 'SUMMARY_TRANSACTION_SUCCESS';
export const SUMMARY_TRANSACTION_FAILURE = 'SUMMARY_TRANSACTION_FAILURE';

export const SUMMARY_STOCK_REQUEST = 'SUMMARY_STOCK_REQUEST';
export const SUMMARY_STOCK_SUCCESS = 'SUMMARY_STOCK_SUCCESS';
export const SUMMARY_STOCK_FAILURE = 'SUMMARY_STOCK_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
